a = input("Enter your full name: ")
b = input("Enter your age: ")
c = input("Enter your school or organization: ")
d = input("What's your dob?: ")

print("\n---------------------------")
print(" VIRTUAL ID CARD ")
print("---------------------------")
print("Name: " + a)
print("Age: " + b)
print("School/Organization: " + d)
print("DOB: " + c)
print("----------Thank you for using my app, bye...-----------------")