name = input("Enter your full name: ")
age = input("Enter your age: ")
school = input("Enter your school or organization: ")
dob = input("What's your dob?: ")

print("\n---------------------------")
print(" VIRTUAL ID CARD ")
print("---------------------------")
print("Name: " + name)
print("Age: " + age)
print("School/Organization: " + school)
print("DOB: " + dob)
print("----------Thank you for using my app, bye...-----------------")