sentence = input("Write a sentence you wrote for a school assignment. ")
old_word = input("Write the word you want to replace. ")
new_word = input("Write the word you want to replace it with. ")

new_sentence_1 = sentence.strip()
print(new_sentence_1)
new_sentence_2 = (sentence.split(","))
print(new_sentence_2)
new_sentence_3 = sentence.title( )
print(new_sentence_3)
new_sentence_4 = (sentence.replace(old_word, new_word))
print(new_sentence_4)
new_sentence_5 = sentence.upper()
print(new_sentence_5)
new_sentence_6 = sentence.lower()
print(new_sentence_6)
new_sentence_7 = (sentence[ : 5])
print(new_sentence_7)


